[phases.setup]
nixPkgs = ["python311", "gcc", "cmake"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app_v90b.py --server.port=$PORT --server.address=0.0.0.0"
